-- enums
create type public.user_role as enum ('super_admin','admin','viewer');
create type public.dashboard_status as enum ('draft','published');

-- profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  role user_role not null default 'admin',
  created_at timestamptz default now()
);

-- dashboards
create table if not exists public.dashboards (
  id uuid primary key default gen_random_uuid(),
  title text not null default 'Untitled Dashboard',
  description text,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  status dashboard_status not null default 'draft',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- widgets
create table if not exists public.dashboard_widgets (
  id uuid primary key default gen_random_uuid(),
  dashboard_id uuid not null references public.dashboards(id) on delete cascade,
  type text not null,
  x int not null default 0,
  y int not null default 0,
  w int not null default 3,
  h int not null default 2,
  config jsonb not null default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- versions
create table if not exists public.dashboard_versions (
  id bigint generated by default as identity primary key,
  dashboard_id uuid not null references public.dashboards(id) on delete cascade,
  version int generated always as identity,
  snapshot jsonb not null,
  created_at timestamptz default now(),
  published_by uuid references public.profiles(id)
);

-- permissions (explicit viewers / editors)
create table if not exists public.dashboard_permissions (
  id uuid primary key default gen_random_uuid(),
  dashboard_id uuid not null references public.dashboards(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  can_edit boolean not null default false,
  can_view boolean not null default true,
  unique(dashboard_id, user_id)
);

-- audit
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor uuid references public.profiles(id),
  action text not null,
  entity text,
  entity_id uuid,
  meta jsonb,
  created_at timestamptz default now()
);
