import dynamic from 'next/dynamic';
import type { WidgetKind } from './types';
export const Registry: Record<WidgetKind, { label: string; component: any }> = {
  kpi:        { label:'KPI', component: dynamic(()=>import('../widgets/KPI')) },
  'multi-kpi':{ label:'Multi KPI', component: dynamic(()=>import('../widgets/MultiKPI')) },
  line:       { label:'Line', component: dynamic(()=>import('../widgets/recharts/LineChartW')) },
  area:       { label:'Area', component: dynamic(()=>import('../widgets/recharts/AreaChartW')) },
  bar:        { label:'Bar', component: dynamic(()=>import('../widgets/recharts/BarChartW')) },
  'stacked-bar':{ label:'Stacked Bar', component: dynamic(()=>import('../widgets/recharts/StackedBarW')) },
  combo:      { label:'Combo', component: dynamic(()=>import('../widgets/recharts/ComboW')) },
  pie:        { label:'Pie', component: dynamic(()=>import('../widgets/recharts/PieW')) },
  donut:      { label:'Donut', component: dynamic(()=>import('../widgets/recharts/DonutW')) },
  treemap:    { label:'Treemap', component: dynamic(()=>import('../widgets/recharts/TreemapW')) },
  scatter:    { label:'Scatter', component: dynamic(()=>import('../widgets/recharts/ScatterW')) },
  bubble:     { label:'Bubble', component: dynamic(()=>import('../widgets/recharts/BubbleW')) },
  radar:      { label:'Radar', component: dynamic(()=>import('../widgets/recharts/RadarW')) },
  radialbar:  { label:'Radial Bar', component: dynamic(()=>import('../widgets/recharts/RadialBarW')) },
  funnel:     { label:'Funnel', component: dynamic(()=>import('../widgets/recharts/FunnelW')) },
  sankey:     { label:'Sankey', component: dynamic(()=>import('../widgets/echarts/SankeyW')) },
  sunburst:   { label:'Sunburst', component: dynamic(()=>import('../widgets/echarts/SunburstW')) },
  heatmap:    { label:'Heatmap', component: dynamic(()=>import('../widgets/echarts/HeatmapW')) },
  histogram:  { label:'Histogram', component: dynamic(()=>import('../widgets/echarts/HistogramW')) },
  boxplot:    { label:'Boxplot', component: dynamic(()=>import('../widgets/echarts/BoxplotW')) },
  waterfall:  { label:'Waterfall', component: dynamic(()=>import('../widgets/echarts/WaterfallW')) },
  gauge:      { label:'Gauge', component: dynamic(()=>import('../widgets/echarts/GaugeW')) },
  table:      { label:'Table', component: dynamic(()=>import('../widgets/TableW')) },
  pivot:      { label:'Pivot', component: dynamic(()=>import('../widgets/PivotW')) },
  slicer:     { label:'Slicer', component: dynamic(()=>import('../widgets/filters/SlicerW')) },
  'date-range':{ label:'Date Range', component: dynamic(()=>import('../widgets/filters/DateRangeW')) },
  'number-range':{ label:'Number Range', component: dynamic(()=>import('../widgets/filters/NumberRangeW')) },
  markdown:   { label:'Markdown', component: dynamic(()=>import('../widgets/MarkdownW')) },
};
